### ISSUE TITLE
Support HTTP2

### ISSUE THREAD

**Issue by krancour** [deislabs/osiris#16]
**What would you like to be added?**

Support for HTTP2.

**Why is this needed?**

HTTP2 is increasingly common, _especially_ as the underlying transport for gRPC.

__N.B.:__ HTTP2 does not strictly require the use of TLS, however, many HTTP2 clients _do_. Mileage from this feature may vary unless/until #15 is also addressed.

**Comment by krancour** [comment]
Similar to [this comment](https://github.com/deislabs/osiris/issues/15#issuecomment-447493133) on #15, this may impact how we approach collecting and aggregating the metrics on which we base scaling decisions.

HTTP2 is capable of multiplexing requests and handling long-lived, full-duplex streams, etc., so a single HTTP2 "request" might logically be thought of in terms more similar to a "connection." This might invalidate our approach of counting requests and drive us toward counting active connections (or "connections") instead.

**Comment by tariq1890** [comment]
Looking into this right now.

**Comment by tariq1890** [comment]
After doing more  reading, I would say that the correct approach is to tackle #15 first given the assumption that http2 is implemented with secure communication(TLS). So I guess we would need to implement the TLS and we could do the HTTP2 on top of  that implementation.

**Comment by krancour** [comment]
@tariq1890, some of the recently opened issues reflect discreet feature requests, but we know implementation details are going to overlap quite a bit. I'm going to open a new issue soon that proposes a comprehensive approach that will address a few of these.

**Comment by krancour** [comment]
This was closed by #27.
