### ISSUE TITLE
Using a label selector to link a service to a deployment

### ISSUE THREAD

**Issue by vbehar** [deislabs/osiris#19]
**Question:**

Hi guys,

quick question: why don't you use a label selector to link the deployment and the service ? instead of using the deployment name.

I'm asking because using the deployment name can be painful, for example when using helm - see https://github.com/helm/helm/issues/2492 for example. It would have been much easier for us to use a label selector.

Thanks

**Comment by vbehar** [comment]
thanks.

So I managed to work-around my helm issue, by using the `tpl` function to execute a template block which is used to retrieve the release name. Something like https://hackernoon.com/the-art-of-the-helm-chart-patterns-from-the-official-kubernetes-charts-8a7cafa86d12#a935

**Comment by krancour** [comment]
> So I managed to work-around my helm issue, by using the tpl function to execute a template block which is used to retrieve the release name.

That's not really a workaround, imo. That's common practice in Helm charts. It's the only way that one resource can ever reference another-- a common example of which would be referencing secrets or config maps when setting an environment variable in a pod. This approach is so ubiquitous, in fact, that when you use `helm create`, it automatically generates such templates for you.
