### ISSUE TITLE
Is Osiris compatible with NodePort services?

### ISSUE THREAD

**Issue by samlevin** [deislabs/osiris#25]
**Question:**
Experimenting with Osiris in minikube. My osiris-flagged pods aren't being zeroscaled after 2.5 minutes, or at all. Logs don't appear to indicate any issues across deployments in the `osiris-system` namespace. The repo example service is of type `LoadBalancer` (and I saw a corresponding Osiris annotation). Is Osiris only compatible with services of this type?

**Comment by krancour** [comment]
@samlevin any luck?

Also, it just occurred to me... pods don't necessarily scale to zero after exactly 2.5 minutes. Pods are checked for evidence of recent activity every 2.5 minutes. If you make even one request toward the beginning of a 2.5 minute period, at the _end_ of that period, no scaling will take place. It will be another 2.5 minutes before it's considered again. This means, depending on timing, you _could_ have nearly 5 minutes elapse before a scale-to-zero event.

**Comment by samlevin** [comment]
Thanks for the reply, and sorry for the delayed response @krancour. I ended up getting it working. Not sure what the initial issue was. But I'm not looking back!
