### ISSUE TITLE
Osiris VS. Knative serving ?

### ISSUE THREAD

**Issue by yogeek** [deislabs/osiris#29]
**Question:**

What are the diffenreces between Osiris and [Knative serving](https://github.com/knative/serving) ?

Thank you !

**Comment by krancour** [comment]
Good question. I'm quite familiar with Knative serving and count myself as a fan, even.

There are a few differences:

1. Scope: Osiris is a bit smaller in scope. It is concerned _exclusively_ with scale to/from zero. It doesn't handle any scaling from n > 1 to m > 1 and suggests that existing mechanisms like HPAs be used to accomplish that.

1. Pre-reqs: Osiris has no dependency on Istio.

1. CRDs: Osiris doesn't introduce any new CRDs or APIs or "model" for what an application looks like. It's driven entirely off of annotations on things you're already familiar with liked deployments and services.

**Comment by yogeek** [comment]
Great, thank you for the details !
