### ISSUE TITLE
chart repo unavailable: 401 Unauthorized

### ISSUE THREAD

**Issue by vbehar** [deislabs/osiris#55]
running `helm repo update` we have the following error:

```
...Unable to get an update from the "osiris" chart repository (https://osiris.azurecr.io/helm/v1/repo):
	Failed to fetch https://osiris.azurecr.io/helm/v1/repo/index.yaml : 401 Unauthorized
```

using the credentials from the README. this used to work for months, and stopped working today.

**Comment by vbehar** [comment]
cc @krancour if you can have a look please. thank you!

**Comment by krancour** [comment]
The credentials expired. I should have it fixed shortly. In the meantime, you should be able to install the chart from source.

**Comment by krancour** [comment]
And thank you for bringing this to my attention.
