### ISSUE TITLE
Supported Helm Version

### ISSUE THREAD

**Issue by JimPaine** [deislabs/osiris#59]
**Question:**
Hi,
 
In the [docs](https://github.com/deislabs/osiris/edit/master/README.md#L64) it says that it can be install with Helm 2.11 or greater, but having tried it with Helm 3.0 I got the following error.

```sh
$ helm repo add osiris https://osiris.azurecr.io/helm/v1/repo --username 'eae9749a-fccf-4a24-ac0d-6506fe2a6ab3' --pass                                                                                                                      word '=s-e.2-84BhIo6LM6=/l4C_sFzxb=sT['
Error: Looks like "https://osiris.azurecr.io/helm/v1/repo" is not a valid chart repository or cannot be reached: error u                                                                                                                      nmarshaling JSON: while decoding JSON: json: cannot unmarshal number into Go struct field ChartVersion.entries.appVersio                                                                                                                      n of type string
```

Thinking it was an unfair test using a new major version I downgraded to 2.16.1 but get the same error. I have now downgraded to 2.11 and I can add the repo successfully.

So my question(s) 
- What versions of Helm can I use and when will 3.0 be supported?

Thanks

**Comment by krancour** [comment]
This is a known issue in recent versions of Helm:

https://github.com/helm/helm/issues/6849

My understanding at this point is that the issue is considered to be how repo indexes are created and _not_ how they're read/parsed later on, and this being the case, it seems the index for this repository needs to be rebuilt. ::sigh::

This is easier said than done. ACR (where this chart repo is hosted) doesn't give users direct control over the index. When we upload new charts, it updates the index for us automatically. i.e. I can't easily rebuild it.

I'm exploring options that range from removing the offending version to starting fresh (there's never been a formal release of this software, so I'm only torpedoing a series of edge releases). Nevertheless, that seems heavy handed.

Stay tuned. In the meantime, stick to Helm < 2.15.

**Comment by krancour** [comment]
For now, I have removed two (very old) versions from the repo where the value in the `appVersion` field could have been mistaken for a float value written in scientific notation.

All versions of Helm should be able to install this repository _for now_.

I will also make changes to the publishing process to ensure we quote the value of the `appVersion` when chart metadata is prepped by `helm package`. (This just requires using a newer version of Helm to package it.)

I'm not sure how ACR will handle that, but I'm optimistic and I will follow up with them if my plan falls apart on their end.

**Comment by krancour** [comment]
I'm updating the containerized tool chain for packaging and publishing charts to (hopefully) avoid the possibility of this happening in the future, but the project that manages that Docker image depends on Circle and they're having issues ATM. I'll have this all fixed up as soon as things clear up, but for the moment, as noted, all versions of Helm should work.

**Comment by krancour** [comment]
Re-opening because although this PR upgraded the Helm tooling, it stopped short of using the commands that actually would improve the situation. #61 is the follow-up.

**Comment by JimPaine** [comment]
Thanks for the quick turn around :D This solved the problem right away!

**Comment by vitarkah** [comment]
helm repo add osiris https://osiris.azurecr.io/helm/v1/repo --username eae9749a-fccf-4a24-ac0d-6506fe2a6ab3 --password =s-e.2-84BhIo6LM6=/l4C_sFzxb=sT[
Error: looks like "https://osiris.azurecr.io/helm/v1/repo" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: unknown field "acrMetadata"

helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

:(

**Comment by krancour** [comment]
@vitarkah I'm not able to replicate your problem.

I did notice, however, that in certain shells (zsh, namely), the leading `=` in the complex password is parsed as an assignment operator. (I was using bash at the time I wrote the instructions.)

Try putting single quotes around the password and see if that makes a difference.
