### ISSUE TITLE
Not able to access the azure container repository to fetch helm chart

### ISSUE THREAD

**Issue by sriram-nappa** [deislabs/osiris#75]
Couldn't fetch the repo using the below creds: 

https://osiris.azurecr.io/helm/v1/repo \
  --username eae9749a-fccf-4a24-ac0d-6506fe2a6ab3 \
  --password =s-e.2-84BhIo6LM6=/l4C_sFzxb=sT[

Throws a 401.

@krancour @yaron2

**Comment by gcasaseca** [comment]
same issue here

**Comment by jordan-gullen-nextdc** [comment]
same issue here

**Comment by krancour** [comment]
Looking into this. I know the repository moved from one Azure subscription to another recently. It's possible the credentials that were once used to access it became invalidated in the process-- hence the 401.

**Comment by krancour** [comment]
This is fixed. Thank you for bringing this to our attention.

**Comment by sriram-nappa** [comment]
@krancour I get this when I try to get the chart 
`<a href="/helm/v1/repo/">Moved Permanently</a>.` 

Is there an update to the chart link?
