### ISSUE TITLE
Does ZeroScaler works with Grpc Services (deployed on Pod) ?

### ISSUE THREAD

**Issue by gautammoulik** [deislabs/osiris#8]
---

### Environment summary
K8s Master Info (e.g. AKS, ACS, Bare Metal, EKS)
AKS
Osiris Version
latest
Install Method (e.g. k8s YAMLs, Helm Chart)
helm chart

### Issue Details
Let me start with, this is not an Issue rather this is a question, I couldn't find a discussion thread/community section where I can ask question. and hence, creating as an issue. 

My question is related to functionalities of the "ZeroScaler", as per the comment in the   Values.yaml file 
[ The interval in which the zeroScaler would repeatedly track the **pod http request metrics**.
 The value is the number of seconds of the interval.
  metricsCheckInterval: 150  ]
If we look at the ":repeatedly track the **pod http request metrics**" part, just to ensure I am on the same page, what if the Pod opens only uses Grpc  ....my understanding is since Grpc uses Http 2 underline, ZeroScaler will still be able to track the Grpc requests .... I mean to say if the Pod doesn't have a typical REST service but it has a Grpc Service, the ZeroScaler will still work ....is my understanding correct ? 
Or does ZeroScaler will not work if the Pod has a Grpc service ... please confirm.

**Comment by krancour** [comment]
I'm going to close this in favor of #16.
