### ISSUE TITLE
Update labels to use to non-reserved prefix

### ISSUE THREAD

**Issue by lachie83** [deislabs/osiris#9]
It has been brought to my attention that the "kubernetes.io" prefix for labels and annotations is reserved and that using it for non-core projects isn't appropriate. 

It's also worth acknowledging that this prefix reservation is not well documented.

**Comment by krancour** [comment]
TIL that we _do_ have a presence at deislabs.io, so I'm going to use osiris.deislabs.io as the keyspace.
